### ISSUE TITLE
Problemas con el archivo .env

### ISSUE THREAD

**Issue by ElAdagioDeJP** [angelopol/bistrot#2]
He identificado una brecha de seguridad en su repositorio. Actualmente, el archivo .gitignore solo contiene una regla para ignorar el archivo .env.produccion, lo que significa que este archivo aparece en todas las ramas. El archivo .env se vuelve visible, exponiendo potencialmente contraseñas y claves de API sensibles.

Para solucionar este problema y asegurar que el archivo .env esté protegido en todas las ramas, deben actualizar el archivo .gitignore para incluir una regla general que ignore el archivo .env en todas las ramas del repositorio. Al final, el archivo .gitignore no está protegiendo el .env en ninguna rama.

**Comment by angelopol** [comment]
La gracia del env.production es almacenar las variables de entorno para el software cuando este en producción, dejando al archivo .env para simplemente almacenar las variables de entorno para desarrollo, las credenciales usadas para el desarrollo no requieren una protección, ya que en su mayoría son usadas para acceder a recursos en local.

**Comment by ElAdagioDeJP** [comment]
Excelente, es que en otros tipos de proyectos el .env si es necesario resguardarlo bien
